// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqe8ipqM2IF_GWtdPYn08w7sqsaRRHgmc',
    appId: '1:1025676648530:web:d60a5a00113cc2182ebf8b',
    messagingSenderId: '1025676648530',
    projectId: 'personalitytest-83542',
    authDomain: 'personalitytest-83542.firebaseapp.com',
    storageBucket: 'personalitytest-83542.firebasestorage.app',
    measurementId: 'G-M9JZGHL73E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLZ_5cDZ-LljwMWG5W7y-TmkUPnMYt3A0',
    appId: '1:1025676648530:android:1221c8cb481d491f2ebf8b',
    messagingSenderId: '1025676648530',
    projectId: 'personalitytest-83542',
    storageBucket: 'personalitytest-83542.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU19iTpCNzhG7wbSmA-34AxzUkAJyk6jk',
    appId: '1:1025676648530:ios:58588ce0b182ee642ebf8b',
    messagingSenderId: '1025676648530',
    projectId: 'personalitytest-83542',
    storageBucket: 'personalitytest-83542.firebasestorage.app',
    iosBundleId: 'com.example.personalityTest',
  );
}
